services:
  postgres:
    image: postgres:16
    container_name: syndic_db
    restart: always
    environment:
      POSTGRES_DB: syndic
      POSTGRES_USER: syndic_user
      POSTGRES_PASSWORD: syndic_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  backend:
    build: ./backend
    container_name: syndic_backend
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: syndic_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"

volumes:
  pgdata:
